<?php
if (!defined("entrypoint"))die;
$labels = array(
    'common' => array(
                      'bc_title' => 'Department of Applied Mathematics',
                      'header_ntuu' => 'NTUU "Kyiv Polytechnic Institute"',
                      'header_pma' => 'Department of Applied Mathematics',
                      'header_fpm' => 'Faculty of Applied Mathematics',
                      'search' => 'Search',
                      'private_place' => 'Private place',
                      'label_pma'=>'Department Of <br/>Applied <br/>Mathematics',
                      'sitemap'=>'Site map',
                     ),

    'news' =>   array(
                      'bc_title' => 'News',
                      'news_is_category' => 'News in category',
                      'no_news' => 'No news',
                      'comments' => 'Comments',
                      'last_news' => 'Last news',
                      'add_comment' => 'Comment',
                      'comment' => 'Comments',
                      'page' => 'Pages',
                      'back'=>'Back'
                     ),

    'login' =>  array(
                      'logout_wrd' => 'Logout',
                      'login_in' => 'Login',
                      'password_wrd' => 'Password',
                      'error_login' => 'Incorrect login or password',
                      'enter_site' => 'Enter site',
                      'login_wrd' => "Login"
                     ),
   'profile' => array (
                        'bc_title' => 'Private Office',
                        'user_profile' => 'User Profile',
                        'university'=>'University',
                        'fio' => 'Name',
                        'yearfinish'=>'Graduation Year',
                        'consultacii'=>'Consultations',
                        'stepen'=>'Academic Degree',
                        'birthday' => 'Birth Date',
                        'sex' => 'Sex',
                        'phone'=>'Phone',
                        'interests'=>'Scientific Interests',
                        'family'=>'Children and Grandchildren, Age',
                        'email' => 'Contact E-mail',
                        'univer_finish'=>'University and the Graduation Year',
                        'change' => 'Change',
                        'change_photo' => 'Change Photo',
                        'set_new_photo' => 'Set New Photo',
                        'user_info' => 'Private Information',
                        'name' => 'First Name',
                        'surname'=>'Last Name',
                        'patronymik' =>'Patronymic',
                        'student_state'=>'Post',
                        'teacher' => 'Lecturer',
                        'status' => 'Status',
                        'male' => 'Male',
                        'work'=>'Career',
                        'hoby'=>'Hobbies',
                        'animal'=>'Pets',
                        "edit"=>'Edit',
                        'female'=>"Female",
                        'save'=>'Save',
                        'group'=>'Group',
                        'profile_user'=>'User profile',
                        'download'=>'Download files',
                        'upgrade'=>'Upload files',
                        'rank' => 'Rank',
                        'student' =>'Student',
                        'praepostor'=>'Praepostor',
                        'trade-union'=>'Proforg',
                        'mail'=>'My messages'
                      ),
    'fileshare' => array(
                        'bc_title' => 'Store of files',
                        'picture'=>'Picture',
                        'download'=>'Download',
                        'description' =>'Description',
                        'file'=>'File',
                        'title'=>'Title',
                        'subject'=>'Subject',
                        'semest'=>'Term',
                        'upload'=>'Upload',
                        'upload_success'=>'File has been successfully uploaded',
                        'error_permition'=>'Permission denied',
                        'error_upload_file' =>'Cannot upload file',
                        'error_file_to_big'=>'File is too big',
                        'error_upload_cover'=>'Cannot upload picture',
                        'error_cover_to_big'=>'Picture is too big',
                        'uploader' =>'Uploader',
                    	'filesize'=>'Filesize'
    ),
    'mail'=>array(
                 'input'=>'Received',
                 'output'=>'Sent',
                 'write'=>'Start a Message',
                 'new_message'=>'New Message',
                 'from'=>'From',
                 'to'=>'To',
                 'Subject'=>'Subject',
                 'message'=>'Message',
                 'send'=>'Send'
    )
);
?>
