<?php
if (!defined("entrypoint"))die;
$labels = array(
    'common' => array(
                      'bc_title' => 'Кафедра Прикладной Математики',
                      'header_ntuu' => 'НТУУ "Киевский Политехнический Институт"',
                      'header_pma' => 'Кафедра Прикладной Математики',
                      'header_fpm' => 'Факультет Прикладной Математики',
                      'search' => 'Поиск',
                      'private_place' => 'Личный кабинет',
                      'label_pma'=>'Кафедра <br/>Прикладной <br/>Математики',
                      'sitemap'=>'Карта сайта',
                     ),

    'news' =>   array(
                      'bc_title' => 'Новости',
                      'news_is_category' => 'Новости в категории',
                      'no_news' => 'Новости отсутствуют',
                      'comments' => 'Комментариев',
                      'comment' => 'Комментарии',
                      'last_news' => 'Последние новости',
                      'add_comment' => 'Комментировать',
                      'page' => 'Страницы',
                      'back'=>'Назад'
                     ),

    'login' =>  array(
                      'logout_wrd' => 'Выйти',
                      'login_in' => 'Вход',
                      'password_wrd' => 'Пароль',
                      'error_login' => 'Неверный логин или пароль',
                      'enter_site' => 'Вход на сайт',
                      'login_wrd' => "Логин"
                     ),
   'profile' => array (
                        'bc_title' => 'Личный кабинет',
                        'university'=>'Университет',
                        'yearfinish'=>'Год окончания',
                        'stepen'=>'Научная степень',
                        'user_profile' => 'Профиль пользователя',
                        'consultacii'=>'Консультации',
                        'interests'=>'Область научных интересов',
                        'family'=>'Дети и внуки, их возраст',
                        'student_state'=>'Должность',
                        'phone'=>'Телефон',
                        'work'=>'Трудовая деятельность',
                        'hoby'=>'Хобби',
                        'animal'=>'Домашние животное',
                        "edit"=>'Редактировать',
                        'fio' => 'Имя',
                        'birthday' => 'Дата рождения',
                        'sex' => 'Пол',
                        'group'=>'Группа',
                        'email' => 'Контактный E-mail',
                        'univer_finish'=>'ВУЗ и год окончания',
                        'change' => 'Изменить',
                        'change_photo' => 'Изменить фото',
                        'set_new_photo' => 'Выбрать новое фото',
                        'user_info' => 'Личная информация',
                        'name' => 'Имя',
                        'surname'=>'Фамилия',
                        'patronymik' =>'Отчество',
                        'student' => "Студент",
                        'teacher' => 'Преподаватель',
                        'status' => 'Статус',
                        'male' => 'Мужчина',
                        'female'=>"Женщина",
                        'save'=>'Сохранить',
                        'profile_user'=>'Профиль пользователя',
                        'download'=>'Скачать файлы',
                        'upgrade'=>'Залить файлы',
                        'rank' => 'Звание',
                        'student' =>'Студент',
                        'praepostor'=>'Староста',
                        'trade-union'=>'Профорг',
                        'mail'=>'Мои сообщения'
                      ),
    'fileshare' => array(
                        'bc_title' => 'Файловое хранилице',
                        'picture'=>'Изображение',
                        'description' =>'Описание',
                        'file'=>'Файл',
                        'download'=>'Скачать',
                        'subject'=>'Предмет',
                        'semest'=>'Семестр',
                        'upload'=>'Закачать',
                        'title'=>'Название',
                        'upload_success'=>'Файл успешно загружен',
                        'error_permition'=>'Недостаточно прав',
                        'error_upload_file' =>'Не могу загрузить файл',
                        'error_file_to_big'=>'Размер файла больше максимально допустимого',
                        'error_upload_cover'=>'Не могу загрузить картинку',
                        'error_cover_to_big'=>'Размер картинки больше максимально допустимого',
                        'uploader' =>'Успешно загружено',
                    	'filesize'=>'Размер файла'
    ),
    'mail'=>array(
                 'input'=>'Входящие',
                 'output'=>'Исходящие',
                 'write'=>'Написать сообщение',
                 'new_message'=>'Новое сообщение',
                 'from'=>'От',
                 'to'=>'Кому',
                 'Subject'=>'Тема',
                 'message'=>'Сообщение',
                 'send'=>'Отправить'
    )
);
?>
