<?php
if (!defined("entrypoint"))die;
$labels = array(
    'common' => array(
                      'bc_title' => 'Кафедра Прикладної Математики',
                      'header_ntuu' => 'НТУУ "Київський Політехнічний Інститут"',
                      'header_pma' => 'Кафедра Прикладної Математики',
                      'header_fpm' => 'Факультет Прикладної Математики',
                      'search' => 'Пошук',
                      'private_place' => 'Особистий кабінет',
                      'label_pma'=>'Кафедра <br/>Прикладної <br/>Математики',
                      'sitemap' => 'Карта сайту',
                     ),

    'news' =>   array(
                      'bc_title' => 'Новини',
                      'news_is_category' => 'Новини в категорії',
                      'no_news' => 'Новини відсутні',
                      'comments' => 'Коментарів',
                      'last_news' => 'Останні новини',
                      'add_comment' => 'Коментувати',
                      'comment' => 'Коментарі',
                      'page' => 'Сторінки',
                      'back'=>'Назад'
                     ),

    'login' =>  array(
                      'logout_wrd' => 'Вийти',
                      'login_in' => 'Вхід',
                      'password_wrd' => 'Пароль',
                      'error_login' => 'Неправильний логін чи пароль',
                      'enter_site' => 'Вхід на сайт',
                      'login_wrd' => "Логін"
                     ),
   'profile' => array (
                        'bc_title' => 'Особистий кабінет',
                        'user_profile' => 'Профіль користувача',
                        'university'=>'Університет',
                        'student_state'=>'Посада',
                        'phone'=>'Телефон',
                        'yearfinish'=>'Рік завершення',
                        'stepen'=>'Науковий ступінь',
                        'fio' => 'Ім’я',
                        'consultacii'=>'Консультації',
                        'interests'=>'Область наукових інтересів',
                        'family'=>'Діти та онуки, їхній вік',
                        'work'=>'Трудова діяльність',
                        'hoby'=>'Хоббі',
                        'animal'=>'Домашні тварини',
                        "edit"=>'Редагувати',
                        'birthday' => 'Дата народження',
                        'sex' => 'Стать',
                        'group'=>'Група',
                        'email' => 'Контактний E-mail',
                        'univer_finish'=>'ВНЗ та рік закінчення',
                        'change' => 'Змінити',
                        'change_photo' => 'Змінити фото',
                        'set_new_photo' => 'Вибрати нове фото',
                        'user_info' => 'Особиста інформація',
                        'name' => 'Ім’я',
                        'surname'=>'Прізвище',
                        'patronymik' =>'По батькові',
                        'student' => "Студент",
                        'teacher' => 'Викладач',
                        'status' => 'Статус',
                        'male' => 'Чоловік',
                        'female'=>"Жінка",
                        'save'=>'Зберегти',
                        'profile_user'=>'Профіль користувача',
                        'mail'=>'Мої повідомлення',
                        'download'=>'Завантажити файли',
                        'upgrade'=>'Залити файли',
                        'rank' => 'Звання',
                        'student' =>'Студент',
                        'praepostor'=>'Староста',
                        'trade-union'=>'Профорг'                        
                      ),

    'rating' => array (
                        'bc_title' => 'Рейтинг студентів',
                        'rating'=>'Рейтинг',
                        'create_table'=>'Створити таблицю',
                        'view_table'=>'Перегляд таблиці',
                        'edit_table'=>'Редагувати таблицю'
    ),
    'fileshare' => array(
                        'bc_title' => 'Файловe сховище',
                        'picture'=>'Зображення',
                        'description' =>'Опис',
                        'file'=>'Файл',
                        'subject'=>'Предмет',
                        'semest'=>'Семестр',
                        'upload'=>'Залити',
                        'title'=>'Назва',
                        'download'=>'Завантажити',
                        'upload_success'=>'Файл успішно залито',
                        'error_permition'=>'Недостатньо прав',
                        'error_upload_file' =>'Не можу завантажити файл',
                        'error_file_to_big'=>'Розмір файлу більший за максимально допустимий',
                        'error_upload_cover'=>'Не можу завантажити зображення',
                        'error_cover_to_big'=>'Розмір зображення більший за максимально допустимий',
                        'uploader' =>'Успішно завантажено',
                    	'filesize'=>'Розмір файлу'
    ),
    'mail'=>array(
                 'input'=>'Отримані',
                 'output'=>'Відправлені',
                 'write'=>'Написати повідомлення',
                 'new_message'=>'Нове повідомлення',
                 'from'=>'Від',
                 'to'=>'Кому',
                 'Subject'=>'Тема',
                 'message'=>'Повідомлення',
                 'send'=>'Відправити',
                 
    )
);
?>
