<?php
if (!defined("entrypoint"))die;
$labels = array(
    'common' => array(
                      'bc_title' => 'Applied Mathematics Department',
                      'header_ntuu' => 'NTUU "Kyiv Polytechnic Institute"',
                      'header_pma' => 'Applied Mathematics Department',
                      'header_fpm' => 'Applied Mathematics Faculty',
                      'search' => 'Search',
                      'private_place' => 'Private place',
                      'label_pma'=>'Applied<br/>Mathematics<br/>Department',
                      'sitemap'=>'Site Map',
                     ),

    'news' =>   array(
                      'bc_title' => 'News',
                      'news_is_category' => 'News in category',
                      'no_news' => 'No news',
                      'comments' => 'Comments',
                      'last_news' => 'Last news',
                      'add_comment' => 'Comment',
                      'comment' => 'Comments',
                      'page' => 'Pages',
                      'back'=>'Back'
                     ),

    'login' =>  array(
                      'logout_wrd' => 'Logout',
                      'login_in' => 'Login',
                      'password_wrd' => 'Password',
                      'double_pass'=>'Repeat password',
                      'error_login' => 'Incorrect login or password',
                      'enter_site' => 'Enter the site',
                      'login_wrd' => "Login"
                     ),
   'profile' => array (
                        'bc_title' => 'Private Office',
                        'user_profile' => 'User Profile',
                        'university'=>'University',
                        'fio' => 'Name',
                        'yearfinish'=>'Graduation Year',
                        'consultacii'=>'Consultations',
                        'stepen'=>'Academic Degree',
                        'birthday' => 'Birth Date',
                        'sex' => 'Sex',
                        'phone'=>'Phone',
                        'interests'=>'Scientific Interests',
                        'family'=>'Children and Grandchildren, Age',
                        'email' => 'Contact E-mail',
                        'univer_finish'=>'University and the Graduation Year',
                        'change' => 'Change Photo',
                        'change_photo' => 'Change Photo',
                        'set_new_photo' => 'Set New Photo',
                        'user_info' => 'Private Information',
                        'name' => 'First Name',
                        'surname'=>'Last Name',
                        'patronymik' =>'Patronymic',
                        'student_state'=>'Post',
                        'teacher' => 'Lecturer',
                        'status' => 'Status',
                        'male' => 'Male',
                        'work'=>'Career',
                        'hoby'=>'Hobbies',
                        'animal'=>'Pets',
                        "edit"=>'Edit',
                        'female'=>"Female",
                        'save'=>'Save',
                        'group'=>'Group',
                        'profile_user'=>'User profile',
                        'download'=>'Download files',
                        'upgrade'=>'Upload files',
                        'rank' => 'Rank',
                        'student' =>'Student',
                        'praepostor'=>'Praepostor',
                        'trade-union'=>'Proforg',
                        'change_pass'=>'Change Password',
                        'pass_not_one'=>'Passwords do not match',
                        'pass_changed'=>'Password successfully changed',
                        'calendar' => 'Calendar'
                      ),
    'rating' => array (
                      'bc_title' => 'Ratings',
                      'rating'=>'Ratings',
                      'create_table'=>'Create table',
                      'view_table'=>'View tables',
                      'edit_table'=>'Edit tables',
                      /* rating_table_edit*/
                      'top_label'=>'Select table',
                      //'editb'=>'Edit columns',
                      'add_label'=>'Add column',
                      'del_label'=>'Delete column',
                      'new_bal_label'=>'Change mark',
                      'addb'=>'add',
                      'delb'=>'del',
                      'editrb'=>'change',
                      'rest'=>'Restore',
                      'savetable'=>'Save',
                      'create_max'=>'Max rating'
                      ),
    'fileshare' => array(
                        'bc_title' => 'Store of files',
                        'picture'=>'Picture',
                        'download'=>'Download',
                        'description' =>'Description',
                        'file'=>'File',
                        'title'=>'Title',
                        'subject'=>'Subject',
                        'semest'=>'Term',
                        'upload'=>'Upload',
                        'upload_success'=>'File has been successfully uploaded',
                        'error_permition'=>'Permission denied',
                        'error_upload_file' =>'Cannot upload file',
                        'error_file_to_big'=>'File is too big',
                        'error_upload_cover'=>'Cannot upload picture',
                        'error_cover_to_big'=>'Picture is too big',
                        'uploader' =>'Uploader',
                    	'filesize'=>'Filesize'
    ),
    'calendar' => array(
                        'monday'=>'Mn',
                        'tuesday'=>'Tu',
                        'wednesday'=>'We',
                        'thursday'=>'Th',
                        'friday'=>'Fr',
                        'saturday'=>'Sa',
                        'sunday'=>'Sn',
                        'month_01'=>'January',
                        'month_02'=>'February',
                        'month_03'=>'March',
                        'month_04'=>'April',
                        'month_05'=>'May',
                        'month_06'=>'June',
                        'month_07'=>'July',
                        'month_08'=>'Augest',
                        'month_09'=>'September',
                        'month_10'=>'October',
                        'month_11'=>'November',
                        'month_12'=>'December',
                        'addMessage'=>'Add Message',
                        'subject'=>'Subject',
                        'messageText'=>'Message',
                        'add'=>'Add',
                        'addSuccess'=>'Message succesfully add',
                        'addError'=>'Could not add',
                        'from'=>'From',
                        'without_subject'=>'Without subject'
    ),
    'mail'=>array('send_message'=>"Send Message",
                  'subject'=>'Subject',
                  'to'=>'To',
                  'message'=>"Message text",
                  'send'=>'Send'
                 )
);
?>
