<?php
if (!defined("entrypoint"))die;
$labels = array(
    'common' => array(
                      'bc_title' => 'Кафедра Прикладної Математики',
                      'header_ntuu' => 'НТУУ "Київський Політехнічний Інститут"',
                      'header_pma' => 'Кафедра Прикладної Математики',
                      'header_fpm' => 'Факультет Прикладної Математики',
                      'search' => 'Пошук',
                      'private_place' => 'Особистий кабінет',
                      'label_pma'=>'Кафедра <br/>Прикладної <br/>Математики',
                      'sitemap' => 'Карта сайту',
                     ),

    'news' =>   array(
                      'bc_title' => 'Новини',
                      'news_is_category' => 'Новини в категорії',
                      'no_news' => 'Новини відсутні',
                      'comments' => 'Коментарів',
                      'last_news' => 'Останні новини',
                      'add_comment' => 'Відкоментувати',
                      'comment' => 'Коментарі',
                      'page' => 'Сторінки',
                      'back'=>'Назад'
                     ),

    'login' =>  array(
                      'logout_wrd' => 'Вийти',
                      'login_in' => 'Вхід',
                      'password_wrd' => 'Пароль',
                      'double_pass'=>'Повторити пароль',
                      'error_login' => 'Неправильний логін чи пароль',
                      'enter_site' => 'Вхід на сайт',
                      'login_wrd' => "Логін"
                     ),
   'profile' => array (
                        'bc_title' => 'Особистий кабінет',
                        'user_profile' => 'Профіль користувача',
                        'university'=>'Університет',
                        'student_state'=>'Посада',
                        'phone'=>'Телефон',
                        'yearfinish'=>'Рік завершення',
                        'stepen'=>'Науковий ступінь',
                        'fio' => 'Ім’я',
                        'consultacii'=>'Консультації',
                        'interests'=>'Область наукових інтересів',
                        'family'=>'Діти та онуки, їхній вік',
                        'work'=>'Трудова діяльність',
                        'hoby'=>'Хоббі',
                        'animal'=>'Домашні тварини',
                        "edit"=>'Редагувати',
                        'birthday' => 'Дата народження',
                        'sex' => 'Стать',
                        'group'=>'Група',
                        'email' => 'Контактний E-mail',
                        'univer_finish'=>'ВНЗ та рік закінчення',
                        'change' => 'Змінити фото',
                        'change_photo' => 'Змінити фото',
                        'set_new_photo' => 'Вибрати нове фото',
                        'user_info' => 'Особиста інформація',
                        'name' => 'Ім’я',
                        'surname'=>'Прізвище',
                        'patronymik' =>'По батькові',
                        'student' => "Студент",
                        'teacher' => 'Викладач',
                        'status' => 'Статус',
                        'male' => 'Чоловік',
                        'female'=>"Жінка",
                        'save'=>'Зберегти',
                        'profile_user'=>'Профіль користувача',
                        'download'=>'Завантажити файли',
                        'upgrade'=>'Залити файли',
                        'rank' => 'Звання',
                        'student' =>'Студент',
                        'praepostor'=>'Староста',
                        'change_pass'=>'Змінити пароль',
                        'trade-union'=>'Профорг',
                        'pass_not_one'=>'Паролі не співпадають',
                        'pass_changed'=>'Пароль успішно змінено',
                        'calendar' => 'Календар'
                      ),

    'rating' => array (
                      'bc_title' => 'Рейтинг студентів',
                      'rating'=>'Рейтинг',
                      'create_table'=>'Створити таблицю',
                      'view_table'=>'Перегляд таблиць',
                      'edit_table'=>'Редагувати таблиці',
                      /* rating_table_edit*/
                      'top_label'=>'Виберіть таблицю',
                      //'editb'=>'Редагувати колонки',
                      'add_label'=>'Додати колонку',
                      'del_label'=>'Видалити колонку',
                      'new_bal_label'=>'Змінити бал',
                      'addb'=>'додати',
                      'delb'=>'видал.',
                      'editrb'=>'змінити',
                      'rest'=>'Відновити',
                      'savetable'=>'Зберегти',
                      'create_max'=>'Максимальный бал'
                      ),
    'fileshare' => array(
                        'bc_title' => 'Файловe сховище',
                        'picture'=>'Зображення',
                        'description' =>'Опис',
                        'file'=>'Файл',
                        'subject'=>'Предмет',
                        'semest'=>'Семестр',
                        'upload'=>'Залити',
                        'title'=>'Назва',
                        'download'=>'Завантажити',
                        'upload_success'=>'Файл успішно залито',
                        'error_permition'=>'Недостатньо прав',
                        'error_upload_file' =>'Не можу завантажити файл',
                        'error_file_to_big'=>'Розмір файлу більший за максимально допустимий',
                        'error_upload_cover'=>'Не можу завантажити зображення',
                        'error_cover_to_big'=>'Розмір зображення більший за максимально допустимий',
                        'uploader' =>'Успішно завантажено',
                    	'filesize'=>'Розмір файлу'
    ),
    'calendar' => array(
                        'monday'=>'Пн',
                        'tuesday'=>'Вт',
                        'wednesday'=>'Ср',
                        'thursday'=>'Чт',
                        'friday'=>'Пт',
                        'saturday'=>'Сб',
                        'sunday'=>'Вс',
                        'month_01'=>'Січень',
                        'month_02'=>'Лютий',
                        'month_03'=>'Березень',
                        'month_04'=>'Квітень',
                        'month_05'=>'Травень',
                        'month_06'=>'Червень',
                        'month_07'=>'Липень',
                        'month_08'=>'Серпень',
                        'month_09'=>'Вересень',
                        'month_10'=>'Жовтень',
                        'month_11'=>'Листопад',
                        'month_12'=>'Грудень',
                        'addMessage'=>'Додати повідомлення',
                        'subject'=>'Тема',
                        'messageText'=>'Повідомлення',
                        'add'=>'Додати',
                        'addSuccess'=>'Повідомлення успішно добавлене',
                        'addError'=>'Не можу додати',
                        'from'=>'Від',
                        'without_subject'=>'Без теми'
    ),
    'mail'=>array('send_message'=>"Відправити повідомлення",
            'subject'=>'Тема',
             'to'=>'Кому',
             'message'=>"Текст повідомлення",
             'send'=>'Відіслати'
        )
);
?>
