<?php
if (!defined("entrypoint"))die;
$labels = array(
    'common' => array(
                      'bc_title' => 'Кафедра Прикладной Математики',
                      'header_ntuu' => 'НТУУ "Киевский Политехнический Институт"',
                      'header_pma' => 'Кафедра Прикладной Математики',
                      'header_fpm' => 'Факультет Прикладной Математики',
                      'search' => 'Поиск',
                      'private_place' => 'Личный кабинет',
                      'label_pma'=>'Кафедра <br/>Прикладной <br/>Математики',
                      'sitemap'=>'Карта сайта',
                     ),

    'news' =>   array(
                      'bc_title' => 'Новости',
                      'news_is_category' => 'Новости в категории',
                      'no_news' => 'Новости отсутствуют',
                      'comments' => 'Комментариев',
                      'comment' => 'Комментарии',
                      'last_news' => 'Последние новости',
                      'add_comment' => 'Откомментировать',
                      'page' => 'Страницы',
                      'back'=>'Назад'
                     ),

    'login' =>  array(
                      'logout_wrd' => 'Выйти',
                      'login_in' => 'Вход',
                      'password_wrd' => 'Пароль',
                      'double_pass'=>'Повторить пароль',
                      'error_login' => 'Неверный логин или пароль',
                      'enter_site' => 'Вход на сайт',
                      'login_wrd' => "Логин"
                     ),
   'profile' => array (
                        'bc_title' => 'Личный кабинет',
                        'university'=>'Университет',
                        'yearfinish'=>'Год окончания',
                        'stepen'=>'Научная степень',
                        'user_profile' => 'Профиль пользователя',
                        'consultacii'=>'Консультации',
                        'interests'=>'Область научных интересов',
                        'family'=>'Дети и внуки, их возраст',
                        'student_state'=>'Должность',
                        'phone'=>'Телефон',
                        'work'=>'Трудовая деятельность',
                        'hoby'=>'Хобби',
                        'animal'=>'Домашние животное',
                        "edit"=>'Редактировать',
                        'fio' => 'Имя',
                        'birthday' => 'Дата рождения',
                        'sex' => 'Пол',
                        'group'=>'Группа',
                        'email' => 'Контактный E-mail',
                        'univer_finish'=>'ВУЗ и год окончания',
                        'change' => 'Изменить фото',
                        'change_photo' => 'Изменить фото',
                        'set_new_photo' => 'Выбрать новое фото',
                        'user_info' => 'Личная информация',
                        'name' => 'Имя',
                        'surname'=>'Фамилия',
                        'patronymik' =>'Отчество',
                        'student' => "Студент",
                        'teacher' => 'Преподаватель',
                        'status' => 'Статус',
                        'male' => 'Мужчина',
                        'female'=>"Женщина",
                        'save'=>'Сохранить',
                        'profile_user'=>'Профиль пользователя',
                        'download'=>'Скачать файлы',
                        'upgrade'=>'Залить файлы',
                        'rank' => 'Звание',
                        'student' =>'Студент',
                        'praepostor'=>'Староста',
                        'trade-union'=>'Профорг',
                        'change_pass'=>'Именить пароль',
                        'pass_not_one'=>'Пароли не совпадают',
                        'pass_changed'=>'Пароль успешно изменен',
                        'calendar' => 'Календарь'
                      ),
    'rating' => array (
                      'bc_title' => 'Рейтинг студентов',
                      'rating'=>'Рейтинг',
                      'create_table'=>'Создать таблицу',
                      'view_table'=>'Просмотр таблиц',
                      'edit_table'=>'Редактировать таблицы',
                      /* rating_table_edit*/
                      'top_label'=>'Выберите таблицу',
                      //'editb'=>'Редактировать колонки',
                      'add_label'=>'Добавить колонку',
                      'del_label'=>'Удалить колонку',
                      'new_bal_label'=>'Изменить бал',
                      'addb'=>'добавить',
                      'delb'=>'удалить',
                      'editrb'=>'изменить',
                      'rest'=>'Сброс',
                      'savetable'=>'Сохранить',
                      'create_max'=>'Максимальный балл'
                      ),
    'fileshare' => array(
                        'bc_title' => 'Файловое хранилице',
                        'picture'=>'Изображение',
                        'description' =>'Описание',
                        'file'=>'Файл',
                        'download'=>'Скачать',
                        'subject'=>'Предмет',
                        'semest'=>'Семестр',
                        'upload'=>'Закачать',
                        'title'=>'Название',
                        'upload_success'=>'Файл успешно залит',
                        'error_permition'=>'Недостаточно прав',
                        'error_upload_file' =>'Не могу загрузить файл',
                        'error_file_to_big'=>'Размер файла больше максимально допустимого',
                        'error_upload_cover'=>'Не могу загрузить картинку',
                        'error_cover_to_big'=>'Размер картинки больше максимально допустимого',
                        'uploader' =>'Успешно загружено',
                    	'filesize'=>'Размер файла'
    ),
    'calendar' => array(
                        'monday'=>'Пн',
                        'tuesday'=>'Вт',
                        'wednesday'=>'Ср',
                        'thursday'=>'Чт',
                        'friday'=>'Пт',
                        'saturday'=>'Сб',
                        'sunday'=>'Вс',
                        'month_01'=>'Январь',
                        'month_02'=>'Февраль',
                        'month_03'=>'Март',
                        'month_04'=>'Апрель',
                        'month_05'=>'Май',
                        'month_06'=>'Июнь',
                        'month_07'=>'Июль',
                        'month_08'=>'Август',
                        'month_09'=>'Сентябрь',
                        'month_10'=>'Октябрь',
                        'month_11'=>'Ноябрь',
                        'month_12'=>'Декабрь',
                        'addMessage'=>'Добавить сообщение',
                        'subject'=>'Тема',
                        'messageText'=>'Сообщение',
                        'add'=>'Добавить',
                        'addSuccess'=>'Сообщение успешно добавлено',
                        'addError'=>'Не могу добавить',
                        'from'=>'От',
                        'without_subject'=>'Без темы'
    )
    ,
    'mail'=>array('send_message'=>"Отправить сообщение",
                  'subject'=>'Тема',
                  'to'=>'Кому',
                  'message'=>"Текст сообщения",
                  'send'=>'Отправить'
        )
);
?>
